INSERT INTO "ACCOUNT" (ID, ENABLED, ACCOUNT_NON_EXPIRED, CREDENTIALS_NON_EXPIRED, ACCOUNT_NON_LOCKED,
                       USERNAME, PASSWORD, EMAIL, MOBILE)
VALUES (1, true, true, true, true, 'admin', '$2a$10$yTB93jkXuk2zLlR98pB8B.yNDUuBaDY.Ct5uHi93LCyrUqUk84cgS', '', '');